name: hupyy-temporal
region: sfo

services:
  - name: web
    github:
      repo: o2alexanderfedin/hupyy-temporal
      branch: develop
      deploy_on_push: true

    dockerfile_path: Dockerfile

    http_port: 8501

    instance_count: 1
    instance_size_slug: basic-xxs

    envs:
      - key: STREAMLIT_SERVER_HEADLESS
        value: "true"
      - key: STREAMLIT_BROWSER_GATHERUSAGESTATS
        value: "false"
      - key: STREAMLIT_SERVER_PORT
        value: "8501"
      - key: STREAMLIT_SERVER_ADDRESS
        value: "0.0.0.0"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: TZ
        value: "UTC"
      - key: CLAUDE_MODEL
        value: "claude-sonnet-3-5-20241022"
      - key: CLAUDE_CODE_OAUTH_TOKEN
        scope: RUN_TIME
        type: SECRET
        value: "${CLAUDE_CODE_OAUTH_TOKEN}"

    health_check:
      http_path: /_stcore/health
      initial_delay_seconds: 60
      period_seconds: 30
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 3

    routes:
      - path: /
